# ROI Pooling Task

- We use the roi_pool function from torchvision to demonstrate the RoI pooling layer computation. 
- Assume that the CNN extracts the feature X with both a height and width of 4 and only a single channel.

In [30]:
import torch
import torchvision
import matplotlib.pyplot as plt
from skimage import io

X = torch.randn(4,4).reshape(1, 1, 4, 4)
X

tensor([[[[-0.7558,  0.8496, -1.5716,  0.3699],
          [-0.7536,  0.3085,  1.8874,  0.9270],
          [ 0.1905,  0.1450,  0.1745, -0.0949],
          [ 1.7927,  0.7481, -1.1700, -0.0633]]]])

- Assume that the height and width of the image are both 40 pixels and that selective search generates two proposed regions on the image. 
- Each region is expressed as five elements: the region’s object category and the  x,y  coordinates of its upper-left and bottom-right corners.

In [31]:
rois = torch.Tensor([[0, 0, 0, 20, 20], [0, 0, 10, 30, 30]])

- Using the same rois, apply ROI pooling on X with an output size (2,2)

In [37]:
#Write your code here
torchvision.ops.roi_pool(X, rois, output_size=(2, 2), spatial_scale=0.1)

tensor([[[[0.8496, 1.8874],
          [0.3085, 1.8874]]],


        [[[0.3085, 1.8874],
          [1.7927, 0.1745]]]])

- Using the same rois, apply ROI pooling on X with an output size (3,3)

In [36]:
#Write your code here
torchvision.ops.roi_pool(X, rois, output_size=(3, 3), spatial_scale=0.1)

tensor([[[[-0.7558,  0.8496, -1.5716],
          [-0.7536,  0.3085,  1.8874],
          [ 0.1905,  0.1450,  0.1745]]],


        [[[ 0.3085,  1.8874,  1.8874],
          [ 0.1905,  0.1745,  0.1745],
          [ 1.7927,  0.7481, -0.0633]]]])